# Generated by Django 4.1.4 on 2022-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(help_text='Enter gmail', max_length=254, verbose_name='Gmail')),
                ('phone_number', models.CharField(help_text='Enter phone_number', max_length=30, verbose_name='Phone_number')),
                ('adress', models.CharField(help_text='Enter adress', max_length=30, verbose_name='Adress')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter title', max_length=30, verbose_name='Title')),
                ('url', models.URLField(help_text='Enter url url', verbose_name='url')),
                ('image', models.ImageField(help_text='Upload images', upload_to='profile-images', verbose_name='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=30, verbose_name='Name')),
                ('image', models.ImageField(help_text='Upload images', upload_to='profile-images', verbose_name='Images')),
                ('age', models.IntegerField(help_text='Enter age', verbose_name='Age')),
                ('technologies', models.TextField(help_text='Enter technologies', verbose_name='technologies')),
                ('job', models.CharField(help_text='enter job', max_length=100, verbose_name='Job')),
                ('resume', models.FileField(help_text='Upload resume', upload_to='resumes', verbose_name='Resume')),
                ('languages', models.CharField(default="O'zbek", help_text='Enter language', max_length=30, verbose_name='Language')),
                ('portfolio', models.IntegerField(default='1', help_text='Enter portfolios count', verbose_name='Portfolio Count')),
                ('profession', models.DecimalField(decimal_places=1, default='1.5', help_text='Enter profession year', max_digits=10, verbose_name='Profession Year')),
                ('project', models.IntegerField(default='1', help_text='Enter project count', verbose_name='Project Count')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(help_text='Enter telegram url', verbose_name='Telegram')),
                ('instagram', models.URLField(help_text='Enter instagram url', verbose_name='Instagram')),
                ('tiktok', models.URLField(help_text='Enter tiktok url', verbose_name='Tiktok')),
                ('facebook', models.URLField(help_text='Enter facebook url', verbose_name='Facebook')),
                ('youtube', models.URLField(help_text='Enter youtube url', verbose_name='Youtube')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
